<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_sidebarBg011627,sidebarTextd6deeb,_3f9f66</name>
   <tag></tag>
   <elementGuidId>07a09f11-603c-49da-8f95-bb069646d290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pasteBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pasteBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pasteBox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{&quot;sidebarBg&quot;:&quot;#011627&quot;,&quot;sidebarText&quot;:&quot;#d6deeb&quot;,&quot;sidebarUnreadText&quot;:&quot;#d6deeb&quot;,&quot;sidebarTextHoverBg&quot;:&quot;#1d3b53&quot;,&quot;sidebarTextActiveBorder&quot;:&quot;#ff2c83&quot;,&quot;sidebarTextActiveColor&quot;:&quot;#82aaff&quot;,&quot;sidebarHeaderBg&quot;:&quot;#1d3b53&quot;,&quot;sidebarHeaderTextColor&quot;:&quot;#d6deeb&quot;,&quot;onlineIndicator&quot;:&quot;#addb67&quot;,&quot;awayIndicator&quot;:&quot;#ffbc42&quot;,&quot;dndIndicator&quot;:&quot;#f74343&quot;,&quot;mentionBg&quot;:&quot;#d6deeb&quot;,&quot;mentionColor&quot;:&quot;#145dbf&quot;,&quot;centerChannelBg&quot;:&quot;#011627&quot;,&quot;centerChannelColor&quot;:&quot;#d6deeb&quot;,&quot;newMessageSeparator&quot;:&quot;#ff8800&quot;,&quot;linkColor&quot;:&quot;#2389d7&quot;,&quot;buttonBg&quot;:&quot;#166de0&quot;,&quot;buttonColor&quot;:&quot;#011627&quot;,&quot;errorTextColor&quot;:&quot;#fd5960&quot;,&quot;mentionHighlightBg&quot;:&quot;#0b2942&quot;,&quot;mentionHighlightLink&quot;:&quot;#82aaff&quot;,&quot;codeTheme&quot;:&quot;solarized-dark&quot;,&quot;mentionBj&quot;:&quot;#ffffff&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pasteBox&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pasteBox']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displaySettings']/div[2]/div[2]/section/div/div/div/div[3]/div/div[4]/div/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy and paste to share theme colors:'])[1]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Button Text'])[1]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Theme Colors'])[1]/preceding::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔ Copied'])[1]/preceding::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='{&quot;sidebarBg&quot;:&quot;#011627&quot;,&quot;sidebarText&quot;:&quot;#d6deeb&quot;,&quot;sidebarUnreadText&quot;:&quot;#d6deeb&quot;,&quot;sidebarTextHoverBg&quot;:&quot;#1d3b53&quot;,&quot;sidebarTextActiveBorder&quot;:&quot;#ff2c83&quot;,&quot;sidebarTextActiveColor&quot;:&quot;#82aaff&quot;,&quot;sidebarHeaderBg&quot;:&quot;#1d3b53&quot;,&quot;sidebarHeaderTextColor&quot;:&quot;#d6deeb&quot;,&quot;onlineIndicator&quot;:&quot;#addb67&quot;,&quot;awayIndicator&quot;:&quot;#ffbc42&quot;,&quot;dndIndicator&quot;:&quot;#f74343&quot;,&quot;mentionBg&quot;:&quot;#d6deeb&quot;,&quot;mentionColor&quot;:&quot;#145dbf&quot;,&quot;centerChannelBg&quot;:&quot;#011627&quot;,&quot;centerChannelColor&quot;:&quot;#d6deeb&quot;,&quot;newMessageSeparator&quot;:&quot;#ff8800&quot;,&quot;linkColor&quot;:&quot;#2389d7&quot;,&quot;buttonBg&quot;:&quot;#166de0&quot;,&quot;buttonColor&quot;:&quot;#011627&quot;,&quot;errorTextColor&quot;:&quot;#fd5960&quot;,&quot;mentionHighlightBg&quot;:&quot;#0b2942&quot;,&quot;mentionHighlightLink&quot;:&quot;#82aaff&quot;,&quot;codeTheme&quot;:&quot;solarized-dark&quot;,&quot;mentionBj&quot;:&quot;#ffffff&quot;}']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/textarea</value>
   </webElementXpaths>
</WebElementEntity>
