<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Run all test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2d7643a5-4bb7-4fca-9332-5e78467629be</testSuiteGuid>
   <testCaseLink>
      <guid>0a2ef2e7-b58d-4b3c-915e-d47c33221e35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/IF_ELSE/TC_Login Fail Notice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00d3315c-ebcf-4f15-944b-71732b483f50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead7150c-993a-4b9b-a50f-334fc2873651</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55e2911e-4b95-4f7a-9654-8dfe0e3a7d9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/IF_ELSE/TC_Login Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>805b99a6-c020-46ea-968c-2af1f098b25d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a976a6c4-3b46-4f91-b35e-12f7adb13533</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94a8a6a0-473e-41f7-b31e-8fc31555588b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/LOOP/TC_Loop Check Setting Block</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d85814b-ce83-4cc4-89c9-f8c267ef3b83</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a238213-8474-4c32-97e2-dc7c7749b91a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/LOOP/TC_Loop Setting Language</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b256be1f-e819-4da6-b514-834da29f1c18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f2c5819-0661-4327-b5fc-28be884e5ede</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/DATA_DRIVEN/INTERNAL/TC_Change Name User</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0ed24191-ae9f-4cb4-9c64-f3e53d9e60e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/DATA_DRIVEN/INTERNAL/TC_Data Change Email</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>57426681-d681-4fd8-9427-6dc59594d960</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/DATA_DRIVEN/INTERNAL/TC_Login User</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cc1a0528-a94c-42e3-8b7c-33432c213bb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drawer Area/Test Add Private Channels</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>304f985b-b660-4c36-add7-fa5e46e4f6d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drawer Area/Test Add Public Channels</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>74e22fe3-1b66-46da-a69a-076cc7ba7871</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drawer Area/Test Create Public Channel Without Name</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>02ff0475-43b2-44e0-a257-851ad172a3ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/API/TC_Change Password Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>287bc93f-d0e8-438a-ad4a-802f9c12132f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e292cd0-38d1-4d96-a919-056f4865a1aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51ee0f52-966b-44db-a5a0-9388798da1fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d062f62-8239-4313-82e2-a8b569e819d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9b20dce-fcd4-400d-9f35-3f460c0555e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/CALL_TC/TC_Check login new password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e061fab5-75d4-4f9b-93d8-f39c3fe41b97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65fd1c77-1344-472c-9df7-d61165246272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a353d95-7d58-46c4-aca4-f5b9470706ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72cc2aa8-a948-4abf-ab8e-5e1c0c8ba7cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6364bd39-4373-4c60-9f72-63bee38429e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2af5bc31-cb9f-4e19-b522-dedcbc927c20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LOGIN_ACCOUNTSETTING/CALL_TC/TC_Logout Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59a4dcee-6c2f-416a-860d-67d4ae66c8f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f89ba3da-613a-4b28-9862-6520d632ac59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b47de38d-edd2-41b8-96ec-3b127db20f5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI_Message_And_Teams_RESTAPI/Teams_RESTAPI/teams</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b771525f-49eb-4410-af41-2bedaf091e40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI_Message_And_Teams_RESTAPI/Teams_RESTAPI/team_for_user</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ae8b82c4-de13-44df-be8f-406dbc6f2c45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI_Message_And_Teams_RESTAPI/Teams_RESTAPI/get_team_by_name</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2411fc4a-cc0c-40c7-aa56-15fe71791f55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI_Message_And_Teams_RESTAPI/Teams_RESTAPI/delete_teams</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d46e0552-625e-47ff-b871-45912f2e8f16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drawer Area/Test Api Create Channel Withou Authentication</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c8d30eab-7f00-48be-8bfc-fae4914f9412</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drawer Area/Test Get Api Channel Without Authentication</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0f3c334d-e4da-4454-977f-bc26942c030c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Drawer Area/Test Get Api Channels</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
